apiVersion: v1
version: 0.1.0
appVersion: 0.1.0
annotations:
  catalog.rancher.io/certified: rancher
  catalog.rancher.io/namespace: monitoring-system
  catalog.rancher.io/release-name: rancher-monitoring-crd
description: A Rancher chart that creates Prometheus Operator CRDs within a cluster.
name: rancher-monitoring-crd

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application